# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: EpiLog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FORCE_COLOR: "1" 

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: |
          python -m pip install -U pip setuptools wheel
          pip install tox

      - name: Use Tox to Orchestrate Unit Testing Paradigm
        run: tox -e py